config/routes.rb
Rails.application.routes.draw do

    root 'posts#index'
    resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
    validates :content, length: { minimum: 50 }
    validates :title, :author, :content, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    def index
        @posts = Post.all
    end
    
    def new
        @post =Post.new
    end
  
    def create
        @post =Post.create(post_params)
        if @post.valid?
            redirect_to root_path
         else
            render :new
        end
    end
    
    def show 
        @post = Post.find(params[:id])
    end
    
    def edit
        @post = Post.find(params[:id])
    end
    
    def update
      @post = Post.find(params[:id])
      @post.update(post_params)
      if @post.valid?
        redirect_to root_path
      else
        render :edit
      end
    end
    
    def destroy
      @post = Post.find(params[:id])
      @post.destroy
      redirect_to root_path
    end
    
    private
    
    def post_params
        params.require(:post).permit(:title, :author, :content)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- wrap -->
  <div id = "wrap">
    <%= render 'shared/nav' %>
    <div class = "container">
      <div class = "row">
        <%= yield %>
      </div>
    </div>
  </div>
<!-- end of wrap -->

  <div class="footer text-center">
    <%= render 'shared/footer' %>
  </div>

</body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<hr>
<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :content %>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/posts/index.html.erb
<div class="modal-body">
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  <span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Add Post
</button>



<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
        <h4 class="modal-title" id="myModalLabel">Add Idea </h4>
      </div>
      <%= simple_form_for Post.new do |f| %>
        <div class="modal-body">
          <%= f.input :title %>
          <%= f.input :author %>
          <%= f.input :content %>
        </div> 
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <%= f.submit 'Submit', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>  

<% @posts.each do |post| %>
  
    <div class="modal-content">
        <blockquote>
          <h3><%= link_to post.title, post_path(post.id) %></h3>
          <small>by <%= post.author %></small>
          <hr>
          <p><%= post.content %></p>
          <br>
          <hr>
        </blockquote>
    </div>
  <br>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= simple_form_for @post do |f| %>
  <%= f.input :title %>
  <%= f.input :author %>
  <%= f.input :content %>
  <%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
          <h3> <%= @post.title %></h3>
          <h5>by  <%= @post.author %> <%= @post.created_at.strftime("%Y-%m-%d") %></h5>
    <hr>
        <div class="panel-body ">
          <p class="content">
          <%= @post.content %>
          </p>
        </div>
    
    <%= link_to 'Delete', post_path(@post), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
    <%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-sm btn-success' %> 
    
        </div>
    </div>
</div>

app/views/shared/_footer.html.erb
<p>© RUJANSHAKYA  <%= Date.today.year %> All Rights Reserved</p>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>                        
      </button>
      <a class="navbar-brand" href="#">Blog</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
      </ul>
      
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'All Ideas', root_path %></li>
        <li><%= link_to 'Add Post', new_post_path %></li>
      </ul>
    </div>
    </div>
    
    
  </div>
</nav>